<%@ include file="/taglibs.jsp" %>
<%@ page import="org.roller.presentation.BasePageModel" %>
<% BasePageModel model = (BasePageModel)request.getAttribute("model"); %>

<p class="subtitle">
    <fmt:message key="bookmarksImport.subtitle" >
    <fmt:param value="${model.website.handle}" />
    </fmt:message>
</p>
<p class="pagetip">
    <fmt:message key="bookmarksImport.prompt" />
</p>     
      
<html:form action="/editor/importBookmarks" method="post" enctype="multipart/form-data">
    <input name="weblog" type="hidden" value='<c:out value="${model.website.handle}" />' />
    <html:file property="bookmarksFile" />
    <br />
    <br />
    <html:submit/></input>
</html:form>

<%--
Added by Matt Raible since the focus javascript generated by Struts uses 
a name reference and IE seems to only focus on file inputs via elements[0]?
--%>
<script type="text/javascript">
<!--
    document.forms[0].elements[0].focus();
// -->
</script>


