<%@ include file="/theme/header.jsp" %>

<h1><fmt:message key="bookmarksImport.title" /></h1>
<p><fmt:message key="bookmarksImport.prompt" /></p>

<html:form action="/importBookmarks" method="post" enctype="multipart/form-data">
    <html:file property="bookmarksFile" />
    <br />
    <br />
    <html:submit/></input>
</html:form>

<%--
Added by Matt Raible since the focus javascript generated by Struts uses 
a name reference and IE seems to only focus on file inputs via elements[0]?
--%>
<script type="text/javascript">
<!--
    document.forms[0].elements[0].focus();
// -->
</script>

<%@ include file="/theme/footer.jsp" %>
