<%-- 
This default stuff goes in the HTML head element of each page
You can override it with your own file via WEB-INF/tiles-def.xml
--%>

<%@ include file="/WEB-INF/jsps/taglibs-struts2.jsp" %>

<%-- the links generated by the Struts-Bootstrap plugin are 404s
<sb:head includeScripts="false" includeScriptsValidation="false"></sb:head>
--%>

<script src="<s:url value='/webjars/jquery/3.3.1/jquery.min.js' />"></script>

<link href="<s:url value='/webjars/jquery-ui/1.12.1/jquery-ui.theme.css' />" rel="stylesheet" />
<script src="<s:url value='/webjars/jquery-ui/1.12.1/jquery-ui.min.js' />"></script>

<link href="<s:url value='/webjars/bootstrap/3.3.7/css/bootstrap.min.css' />" rel="stylesheet" />
<link href="<s:url value='/webjars/bootstrap/3.3.7/css/bootstrap-theme.min.css' />" rel="stylesheet" />
<script src="<s:url value='/webjars/bootstrap/3.3.7/js/bootstrap.min.js' />"></script>

<%-- roller Javascropt and styles --%>
<link rel="stylesheet" media="all" href='<s:url value="/roller-ui/styles/roller.css"/>' />
<script src="<s:url value="/theme/scripts/roller.js"/>"></script>
