
-- Migration of Roller 1.2 to 1.3 database schema.

-- -----------------------------------------------------

-- For ROL-754. MySQL 5.x introduced a new keyword "condition"
-- which made the use of "condition" as a column name in the "pingtarget" table illegal.
-- This renames the column to "conditioncode".   There is a corresponding change in the
-- Hibernate mapping metadata.

-- Create the new column.  If your database will not autopopulate new columns with default values, you may
-- have to remove the "not null" clause here.
alter table pingtarget add column conditioncode integer default 0 not null;

-- Transfer old column data to the new column.  This is not critical as currently it is not used, and
-- later the data will be generated by usage in the ping processor.
update pingtarget pt set pt.conditioncode=pt.condition;

-- Drop the old column.
alter table pingtarget drop column condition;

-- -----------------------------------------------------