
-- User permissions within a website
-- permission_mask: bitmask 001 limited, 011 author, 100 admin
-- pending: pending user acceptance of invitation to join website
create table roller_user_permissions (
    id              varchar(48) not null primary key,
    website_id      varchar(48) not null,
    user_id         varchar(48) not null,
    permission_mask integer not null, 
    pending         @BOOLEAN_SQL_TYPE_TRUE@ not null
);

-- Add new handle field to uniquely identify websites in URLs
alter table website add column handle varchar(255) @ALTER_TABLE_NOT_NULL@;
alter table website add column datecreated  timestamp @ALTER_TABLE_NOT_NULL@;
alter table website add column emailaddress varchar(255) @ALTER_TABLE_NOT_NULL@;
create index website_handle_index on website(handle);
alter table website add constraint website_handle_uq unique (handle@INDEXSIZE@);

-- Add userid to weblogentry so we can track original creator of entry
alter table weblogentry add column userid varchar(48) @ALTER_TABLE_NOT_NULL@;
alter table weblogentry add column status varchar(20) @ALTER_TABLE_NOT_NULL@;
create index weblogentry_userid_index on weblogentry(userid);

alter table rolleruser add column isenabled @BOOLEAN_SQL_TYPE_TRUE@ @ALTER_TABLE_NOT_NULL@;
alter table rolleruser add column locale varchar(50) @ALTER_TABLE_NOT_NULL@;
alter table rolleruser add column timezone varchar(50) @ALTER_TABLE_NOT_NULL@;
create index user_isenabled_index on rolleruser( isenabled );

-- -----------------------------------------------------

insert roller_properties (name,value) values ('site.shortName','');
insert roller_properties (name,value) values ('planet.cache.dir','/var/roller/planet-cache');

-- -----------------------------------------------------

-- Audit log records time and comment about change
-- user_id: user that made change
-- object_id: id of associated object, if any
-- object_class: name of associated object class (e.g. WeblogEntryData)
-- comment: description of change
-- change_time: time that change was made
create table roller_audit_log (
    id              varchar(48) not null primary key,
    user_id         varchar(48) not null,  
    object_id       varchar(48),           
    object_class    varchar(255),          
    comment         varchar(255) not null, 
    change_time     timestamp              
);

-- -----------------------------------------------------
-- For ROL-754. MySQL 5.x introduced a new keyword "condition"
-- which made the use of "condition" as a column name in the "pingtarget" table illegal.
-- This renames the column to "conditioncode".   There is a corresponding change in the
-- Hibernate mapping metadata.

-- Create the new column.  If your database will not autopopulate new columns with default values, you may
-- have to remove the "not null" clause here.
alter table pingtarget add column conditioncode integer default 0 not null;

-- Transfer old column data to the new column.  This is not critical as currently it is not used, and
-- later the data will be generated by usage in the ping processor.
update pingtarget pt set pt.conditioncode=pt.condition;

-- Drop the old column.
alter table pingtarget drop column condition;
-- -----------------------------------------------------
