<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  The ASF licenses this file to You
  under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.  For additional information regarding
  copyright in this work, please see the NOTICE file in the top level
  directory of this distribution.
-->
<%@ include file="/taglibs.jsp" %>
<%@ page import="org.apache.roller.ui.core.BasePageModel" %>
<% BasePageModel model = (BasePageModel)request.getAttribute("model"); %>

<p class="subtitle">
    <fmt:message key="bookmarksImport.subtitle" >
    <fmt:param value="${model.website.handle}" />
    </fmt:message>
</p>
<p class="pagetip">
    <fmt:message key="bookmarksImport.prompt" />
</p>     
      
<html:form action="/roller-ui/authoring/importBookmarks" method="post" enctype="multipart/form-data">
    <input name="weblog" type="hidden" value='<c:out value="${model.website.handle}" />' />
    <html:file property="bookmarksFile" />
    <br />
    <br />
    <html:submit/></input>
</html:form>

<%--
Added by Matt Raible since the focus javascript generated by Struts uses 
a name reference and IE seems to only focus on file inputs via elements[0]?
--%>
<script type="text/javascript">
<!--
    document.forms[0].elements[0].focus();
// -->
</script>


