<%@ include file="/taglibs.jsp" %><%@ include file="/theme/header.jsp" %>

<roller:StatusMessage/>

<html:form action="/editor/page" method="post">

	<h1><fmt:message key="pageForm.editPage" />:<bean:write name="weblogTemplateForm" property="name" /></h1>
	
    <table>
        <tr>
            <td><fmt:message key="pageForm.name" /><br />
            <html:text property="name" size="50"/>
            </td>
        </tr>
        <tr>
            <td><fmt:message key="pageForm.link" /><br />
            <html:text property="link" size="50"/>
            </td>
        </tr>
        <tr>
            <td><fmt:message key="pageForm.description" /><br />
            <html:textarea property="description" rows="3" cols="50"/>
            </td>
        </tr>
        <tr>
            <td><fmt:message key="pageForm.template" /><br />
            <html:textarea property="contents" cols="80" rows="30" style="width: 100%" />
            </td>
        </tr>
    </table>

    <html:hidden property="id"/>
    <html:hidden property="name"/>

    <br />
    <input type="submit" value='<fmt:message key="pageForm.save" />' /></input>
    <html:hidden property="method" value="update"/>

</html:form>

<%--
Added by Matt Raible since the focus javascript generated by Struts 
doesn't seem to work for forms with duplicate named elements.
--%>
<script type="text/javascript">
<!--
    document.forms[0].elements[0].focus();
// -->
</script>

<%@ include file="/theme/footer.jsp" %>


