/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  The ASF licenses this file to You
 * under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.  For additional information regarding
 * copyright in this work, please see the NOTICE file in the top level
 * directory of this distribution.
 */

package org.apache.roller.weblogger.ui.core.filters;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Filter checks all POST request for presence of valid salt value and rejects those without
 * a salt value or with a salt value not generated by this Roller instance.
 */
public class ValidateSaltFilter implements Filter {
    private static final Log log = LogFactory.getLog(ValidateSaltFilter.class);

    @Override
    public void doFilter(ServletRequest request, ServletResponse response,
            FilterChain chain) throws IOException, ServletException {
        HttpServletRequest httpReq = (HttpServletRequest) request;

        if ("POST".equalsIgnoreCase(httpReq.getMethod())) {
            if (SaltValidator.isMultipartFormPost(httpReq) && isStrutsAction(httpReq)) {
                // Struts wraps multipart requests before its interceptor stack;
                // ValidateSaltInterceptor handles these requests.
                chain.doFilter(request, response);
                return;
            }

            try {
                SaltValidator.requireSubmittedSalt(httpReq);
            } catch (ServletException e) {
                if (log.isDebugEnabled()) {
                    log.debug("Valid salt value not found on POST to URL : "
                            + httpReq.getServletPath());
                }
                throw e;
            }
        }

        chain.doFilter(request, response);
    }

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
    }

    @Override
    public void destroy() {
    }

    private boolean isStrutsAction(HttpServletRequest request) {
        String servletPath = request.getServletPath();
        return servletPath != null && servletPath.endsWith(".rol");
    }
}
