package org.apache.roller.planet.ui.admin.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="planetSubscriptionForm"
 */
public class PlanetSubscriptionForm
    extends    org.apache.struts.action.ActionForm
    implements java.io.Serializable
{
    protected java.util.Set groups;
    protected java.lang.String id;
    protected java.lang.String feedURL;
    protected java.util.Date lastUpdated;
    protected java.lang.String siteURL;
    protected java.lang.String title;
    protected java.lang.String author;
    protected int inboundlinks;
    protected int inboundblogs;
    protected java.lang.String name;
    protected java.lang.String URL;
    protected java.util.List entries;

    /** Default empty constructor. */
    public PlanetSubscriptionForm() {}

    /** Constructor that takes the data object as argument. */
    public PlanetSubscriptionForm(org.apache.roller.planet.pojos.PlanetSubscriptionData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.util.Set getGroups()
    {
        return this.groups;
    }

   /** 
    */
    public void setGroups( java.util.Set groups )
    {
        this.groups = groups;
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.String getFeedURL()
    {
        return this.feedURL;
    }

   /** 
    */
    public void setFeedURL( java.lang.String feedURL )
    {
        this.feedURL = feedURL;
    }

    public java.util.Date getLastUpdated()
    {
        return this.lastUpdated;
    }

   /** 
    */
    public void setLastUpdated( java.util.Date lastUpdated )
    {
        this.lastUpdated = lastUpdated;
    }

    public java.lang.String getSiteURL()
    {
        return this.siteURL;
    }

   /** 
    */
    public void setSiteURL( java.lang.String siteURL )
    {
        this.siteURL = siteURL;
    }

    public java.lang.String getTitle()
    {
        return this.title;
    }

   /** 
    */
    public void setTitle( java.lang.String title )
    {
        this.title = title;
    }

    public java.lang.String getAuthor()
    {
        return this.author;
    }

   /** 
    */
    public void setAuthor( java.lang.String author )
    {
        this.author = author;
    }

    public int getInboundlinks()
    {
        return this.inboundlinks;
    }

   /** 
    */
    public void setInboundlinks( int inboundlinks )
    {
        this.inboundlinks = inboundlinks;
    }

    public int getInboundblogs()
    {
        return this.inboundblogs;
    }

   /** 
    */
    public void setInboundblogs( int inboundblogs )
    {
        this.inboundblogs = inboundblogs;
    }

    public java.lang.String getName()
    {
        return this.name;
    }

   /** 
    */
    public void setName( java.lang.String name )
    {
        this.name = name;
    }

    public java.lang.String getURL()
    {
        return this.URL;
    }

   /** 
    */
    public void setURL( java.lang.String URL )
    {
        this.URL = URL;
    }

    public java.util.List getEntries()
    {
        return this.entries;
    }

   /** 
    */
    public void setEntries( java.util.List entries )
    {
        this.entries = entries;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.planet.pojos.PlanetSubscriptionData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setFeedURL(this.feedURL);

        dataHolder.setLastUpdated(this.lastUpdated);

        dataHolder.setSiteURL(this.siteURL);

        dataHolder.setTitle(this.title);

        dataHolder.setAuthor(this.author);

        dataHolder.setInboundlinks(this.inboundlinks);

        dataHolder.setInboundblogs(this.inboundblogs);

        dataHolder.setTitle(this.name);
    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.planet.pojos.PlanetSubscriptionData dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.feedURL = dataHolder.getFeedURL();

        this.lastUpdated = dataHolder.getLastUpdated();

        this.siteURL = dataHolder.getSiteURL();

        this.title = dataHolder.getTitle();

        this.author = dataHolder.getAuthor();

        this.inboundlinks = dataHolder.getInboundlinks();

        this.inboundblogs = dataHolder.getInboundblogs();

        this.name = dataHolder.getName();

        this.URL = dataHolder.getURL();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.feedURL = null;

        this.lastUpdated = null;

        this.siteURL = null;

        this.title = null;

        this.author = null;

        this.inboundlinks = 0;

        this.inboundblogs = 0;

        this.name = null;

        this.URL = null;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
