#!/bin/bash

export GROOVY_HOME=~/java/groovy
export ROLLER_HOME=~/roller_trunk/build/webapp
export JDBCJAR=$CATALINA_HOME/common/lib/mysql-connector-java-3.1.13-bin.jar
#export JDBCJAR=$CATALINA_HOME/common/lib/derbyclient.jar

#export GROOVY_HOME=~/java/groovy
#export ROLLER_HOME=../../standalone/build/roller-demo/webapps/roller
#export JDBCJAR=../../standalone/build/roller-demo/common/lib/hsqldb.jar

export CLASSPATH=.:\
${GROOVY_HOME}/embeddable/groovy-all-1.0-jsr-05.jar:\
${GROOVY_HOME}/lib/commons-cli-1.0.jar:\
${ROLLER_HOME}/WEB-INF/lib/roller-business.jar:\
${ROLLER_HOME}/WEB-INF/lib/roller-web.jar:\
${ROLLER_HOME}/WEB-INF/classes:\
${JDBCJAR}:\
${ROLLER_HOME}/WEB-INF/lib/hibernate3.jar:\
${ROLLER_HOME}/WEB-INF/lib/dom4j-1.6.1.jar:\
${ROLLER_HOME}/WEB-INF/lib/ehcache-1.1.jar:\
${ROLLER_HOME}/WEB-INF/lib/jta.jar:\
${ROLLER_HOME}/WEB-INF/lib/cglib-2.1.3.jar:\
${ROLLER_HOME}/WEB-INF/lib/asm.jar:\
${ROLLER_HOME}/WEB-INF/lib/asm-attrs.jar:\
${ROLLER_HOME}/WEB-INF/lib/jdom.jar:\
${ROLLER_HOME}/WEB-INF/lib/rome-0.8.jar:\
${ROLLER_HOME}/WEB-INF/lib/rome-fetcher-0.8.jar:\
${ROLLER_HOME}/WEB-INF/lib/log4j-1.2.11.jar:\
${ROLLER_HOME}/WEB-INF/lib/commons-logging.jar:\
${ROLLER_HOME}/WEB-INF/lib/commons-collections.jar:\
${ROLLER_HOME}/WEB-INF/lib/commons-lang-2.0.jar
java -classpath ${CLASSPATH} groovy.lang.GroovyShell $1 $2 $3

